branches:
  - main

floating_tags: true

version_files:
  - package.json

changelog:
  file: CHANGELOG.md

commit_types:
  chore: patch

hooks:
  pre_release:
    - npm run build
    - npm test
    - git add -f dist/
